version: '3.8'

services:
  pytorch-dev:
    # Use the specified NGC PyTorch image
    image: nvcr.io/nvidia/pytorch:25.08-py3

    # To enable GPU access, we need to specify the runtime.
    # The 'gpus' key is the modern way to do this.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    # Map local directories to directories inside the container.
    # Replace the paths on the left with your actual local paths.
    volumes:
      # Volume for your Python code and scripts
      - ../:/app/code
      # Volume for your datasets
      - /mnt/d/xuyz/datasets:/app/data
    
    # Increase /dev/shm to 8 GB
    shm_size: 8gb

    # A long-running command to keep the container alive.
    # This allows you to attach to it later using 'docker compose exec'.
    command: sleep infinity

